### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by onokatio** [tipxem/tipxem#1]
## TODO list

- [ ] create database table example
- [ ] create MAKEFILE
- [ ] use exception
- [ ] create wiki abut how to use
- [ ] use 1byte spaces word.
- [ ] streaming API & REST API hybrid

**Comment by onokatio** [comment]
projectに移行
